### ISSUE TITLE
Please add a license to your repository :-)

### ISSUE THREAD

**Issue by arfon** [yohanboniface/carto-atom#1]
Hello there, we'd like to use this grammar to enable syntax-highlighting of CartoCSS on GitHub.com: https://github.com/github/linguist/pull/1933

Do you think you could add a license to this repository? MIT is preferred but there are lots of options available: http://choosealicense.com

Thanks in advance and happy new year :tada:

**Comment by yohanboniface** [comment]
Sure :)

[package.json](https://github.com/yohanboniface/carto-atom/blob/master/package.json) says it's WTFPL, does that suit your needs? If yes, I'll add a proper LICENCE file. If not, I can switch to MIT, that'd be fine too.

**Comment by arfon** [comment]
> Sure :)

Awesome, thanks! If possible a proper license file would be great. Also, while I think WTFPL is _probably_ ok, MIT or Apache2 is definitely preferred.

**Comment by yohanboniface** [comment]
Gone with MIT :)

**Comment by arfon** [comment]
:zap: thanks for the rapid turnaround!
