### ISSUE TITLE
Update for mapnik-reference 8.x.x

### ISSUE THREAD

**Issue by gravitystorm** [yohanboniface/carto-atom#3]
The mapnik-reference is now on the 8.x.x series, and includes a few new attributes for mapnik 3 that aren't in the currently used 6.0.4 version of mapnik-reference.

**Comment by yohanboniface** [comment]
Good point :)

Should be published, now :)

(I was waiting for mapnik/mapnik-reference#109, but it seems now it's more complicated since mapnik/mapnik-reference#111…)

**Comment by gravitystorm** [comment]
Thanks! Great package by the way, I only found it recently but it's very useful.
